### ISSUE TITLE
Crash on Kodi 18.6 Leia. Xbox one S

### ISSUE THREAD

**Issue by thatsmesaurav** [croneter/repository.plexkodiconnect#2]
I am facing a crash on XBOX one S during the sync with Plex. 
Works on my Linux Kodi so I guess plex is setup fine.  

Log is located at:
https://paste.kodi.tv/lecoladana

**Comment by croneter** [comment]
Hmm, weird, Python or Kodi does not detect that you're running Kodi on an Xbox.

Solution: in the PKC settings under Sync, manually deactivate synching of playlists. Then restart Kodi

**Comment by croneter** [comment]
By the way - please don't post issues here but on the main PlexKodiConnect github page :wink:

**Comment by thatsmesaurav** [comment]
I will post future issues to the main github page. 
Came here from Readme Submit issues. You should point that to the main PlexKodiConnect github page, would help people like me.  :)

Regards
